using Cryptlex.Net.Core;
using Cryptlex.Net.Factories;
using Cryptlex.Net.Licenses;

var cryptlexClientSettings = new CryptlexClientSettings() { AccessToken = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJhY2NvdW50OnJlYWQiLCJhY2NvdW50OndyaXRlIiwiYWN0aXZhdGlvbjpyZWFkIiwiYW5hbHl0aWNzOnJlYWQiLCJlbWFpbFRlbXBsYXRlOnJlYWQiLCJlbWFpbFRlbXBsYXRlOndyaXRlIiwiZXZlbnRMb2c6cmVhZCIsImZlYXR1cmVGbGFnOnJlYWQiLCJmZWF0dXJlRmxhZzp3cml0ZSIsImludm9pY2U6cmVhZCIsImxpY2Vuc2U6cmVhZCIsImxpY2Vuc2U6d3JpdGUiLCJsaWNlbnNlUG9saWN5OnJlYWQiLCJsaWNlbnNlUG9saWN5OndyaXRlIiwibWFpbnRlbmFuY2VQb2xpY3k6cmVhZCIsIm1haW50ZW5hbmNlUG9saWN5OndyaXRlIiwicGF5bWVudE1ldGhvZDpyZWFkIiwicGF5bWVudE1ldGhvZDp3cml0ZSIsInBlcnNvbmFsQWNjZXNzVG9rZW46d3JpdGUiLCJwcm9kdWN0OnJlYWQiLCJwcm9kdWN0OndyaXRlIiwicHJvZHVjdFZlcnNpb246cmVhZCIsInByb2R1Y3RWZXJzaW9uOndyaXRlIiwicmVsZWFzZTpyZWFkIiwicmVsZWFzZTp3cml0ZSIsInJvbGU6cmVhZCIsInJvbGU6d3JpdGUiLCJzZW5kaW5nRG9tYWluOnJlYWQiLCJzZW5kaW5nRG9tYWluOndyaXRlIiwidGFnOnJlYWQiLCJ0YWc6d3JpdGUiLCJ0cmlhbEFjdGl2YXRpb246cmVhZCIsInRyaWFsQWN0aXZhdGlvbjp3cml0ZSIsInRyaWFsUG9saWN5OnJlYWQiLCJ0cmlhbFBvbGljeTp3cml0ZSIsInVzZXI6cmVhZCIsInVzZXI6d3JpdGUiLCJ3ZWJob29rOnJlYWQiLCJ3ZWJob29rOndyaXRlIl0sInN1YiI6IjJhYWU0NDgwLTQzNWMtNGJmYi1iMTdmLTcwMTcwZDliOTJhOCIsImVtYWlsIjoibWVqZXZpbkBnbWFpbC5jb20iLCJqdGkiOiI2NTc4NzljZC04YWY5LTQ5MTgtODRmMC02ZTM3MjFkOTI4MGQiLCJpYXQiOjE2NTY3MjU4OTUsInRva2VuX3VzYWdlIjoicGVyc29uYWxfYWNjZXNzX3Rva2VuIiwidGVuYW50aWQiOiJlMjQ3M2EzNy1kMDdkLTQ3NWUtOGU0Yi0wODQ3NWZiMjZkOWIiLCJleHAiOjE2NjkyMzcyMDAsImF1ZCI6Imh0dHBzOi8vYXBpLmNyeXB0bGV4LmNvbSJ9.dfrgKNRjNkRoxe5MFpBx5nCYhGXXhWbW0V8MZtMMiLkQbSt_BrFFzc3ZXvwe1UBPaYgsPwBM5FXEaVYE66CSTYxXXS3mD_NNY_ECbqNX46_oC1lNV_6Htv2TehC1Wmzx2-Zj5Sh1nVMceXHZgYaiEsmQdx0MO-P9L7K5E8vYSolbQs5dA28RvdHmecg0pzIbcMy1HfpFUJUvblnO7_aaPyKwISDJSwX8KtCDYHd3DiHSTXW4wQyJ6V-IRyTr1ztR8Pb3UumI4xRRLhdyTEMETJCHxARwFFOThCWn54UEduIn2tMRHMbY7qtd0fPaGZctwXPD9oQqdfwnJY5dNWeQnQ" };

var cryptlexClient = CryptlexClientFactory.Create(cryptlexClientSettings);

Console.WriteLine("Fetching licenses from cryptlex...\n");

var licenses = await cryptlexClient.Licenses.ListAsync(new ListLicensesData() { page = 2 });

Console.WriteLine($"\nDone! Got {licenses.Count()} licenses from cryptlex: ");
foreach (var license in licenses) Console.WriteLine(license.Id);
Console.WriteLine();

Console.ReadKey();